OPENAI_API_KEY: bashrc

prompt: |
  You can control a robot agent of Go1 quadruped robot.
  You will take natural language user command. 
  Your task is to select the appropriate action among the candidates.

  Here is the list of candidates:
  ACTION_CANDIDATES

  And here is the user command:
  USER_COMMAND

  Your response should be formatted as follows:
  ```python
  ACTION_NAME
  ```
  RULES FOR MISSION INVOLVING CONE:
    If the user specifies a color (red, blue, green), add it as a parameter of the form (redcone, bluecone, greencone):
    Example: User "Find the red cone" -> Response: 
    ```python
    mission_3_cone.py --ros-args -p target_color:=redcone
    ```
action_candidates:
  node:
    - stop.py
    - go_front.py
    - go_back.py 
    - mission_1_toilet.py 
    - mission_3_cone.py
    - mission_5_emptyroom.py
    - mission_6_nurse.py
  launch:
    - go_back.launch.py